version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - t-ober
  - sensarmad
  - sebastian-peter
  - danielfeismann
  - jo-bao

- package-ecosystem: pip
  directory: "/docs/readthedocs"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 8
  target-branch: dev
